#include <iostream>
#include <fstream>
#include <cstdio>
#include <list>

using namespace std;

// 只有本身是常量值才能标记成常量的表达式
constexpr const char g_szTokenTAZKIRA[] = { "TAZKIRA" };
constexpr const char g_szTokenTASKERA[] = { "TASKERA" };


// constexpr const string g_szTokenTASKERA2 { "TASKERA", "test"};
constexpr const char* strarray[] = { "hey", "sup", "dogg" };
std::list<string> values = { "hey", "sup", "dogg", "BOSNIAN","C.U.I.", "C.U.I.P.", "C.U.I.T." , "C.U.R.P.", "CARTILLA", "CITIZEN'S", "CNP", "CREDENCIAL",
"D.N.I.", "ELECTORAL", "I.F.E.",  "KENYAN", "NUMERO", "PERSONAL", "SERIAL", "TURKISH"
};

// ostringstream ossExpectedBIC;

struct MyStruct
{
    char charArray[301];
};

// 在原有的字符数组中拼加额外的数据
string combineExtraData(char* sourceData, string extraData) {
    string source = std::string(sourceData);
    if (!source.empty()) {
        source.append(" ");
    }
    source.append(extraData);
    // strcat(sourceData, (" " + extraData).c_str());

    return source;
}

int mainTest() {

    list<string> strList = { "add.csv", "comments.csv", "sdn.csv" };
    strList.remove("comments.csv");
    for (auto item : strList) {
        std::cout << item << " ";
    }

    std::cout << 3 / 4 << std::endl;
    std::cout << 4 / 4 << std::endl;


    char charArray[10000] = "WEBSITE ALT. https//www;c WEBSIT DIGITAL CURRENCY ADDRESS - XBT 3K4RJDH8A5YI6LWVFT2RBMYZVQEBPSSSX4; ALT. DIGITAL CURRENCY ADDRESS - XBT 17MHYEBX617ABZ1FFTHHUTJKHUCMVCKFD5; ALT. DIGITAL CURRENCY ADDRESS - XBT 35QWVTMEOHWDDBWRICSR7AZOP5CBY8SG1Q; ALT. DIGITAL CURRENCY ADDRESS - XBT 35KADTA2VQNJZITF2XIUZZN1GMCAS2Y465; ALT. DIGITAL CURRENCY ADDRESS - XBT 35LSCRJ8HZDVVWH9T9UA8BHGNGNVZ3YEFA; ALT. DIGITAL CURRENCY ADDRESS - XBT 1PJP8DINA89CVHPIT1VPU7EQ8LXYM5HX6V; ALT. DIGITAL CURRENCY ADDRESS - XBT 17V7THWHMIDJMDWZK4UNHE5HGKFJKX7VCE; ALT. DIGITAL CURRENCY ADDRESS - XBT 3PICNZRBVGFWAKQ9HR4CCPFADJY64YNSPE; ALT. DIGITAL CURRENCY ADDRESS - XBT 14GM1HULVDELNHAFU22QPABJTIWEK4HHV1; ALT. DIGITAL CURRENCY ADDRESS - XBT 1GYUU9D5HPIKAFBYS3K5Q3DRJQ6DEBGSOB; ALT. DIGITAL CURRENCY ADDRESS - XBT 3GXDTA6KBB4M5AQZZM5QQXCFDFRMW8LQDJ; ALT. DIGITAL CURRENCY ADDRESS - XBT 1B11EZQG3AXJFHMDRQ5UPPDPNYRIYNVTKN; ALT. DIGITAL CURRENCY ADDRESS - XBT 16SPDQFFZGSONSPIFFTFS8DW8LLXQIA4OC; ALT. DIGITAL CURRENCY ADDRESS - XBT 19PPBUDVOSBZAFKUCYKD2Z9AKUQQV6SWM7; ALT. DIGITAL CURRENCY ADDRESS - XBT 3BQACTIMXYB9JPUMPKEWT9M8BZSWPGHQ4X; ALT. DIGITAL CURRENCY ADDRESS - XBT 1DGSY4WW3BJNWXTSNMTGWA6UWDORXGA1PX; ALT. DIGITAL CURRENCY ADDRESS - XBT 1GCKLUUXODTQCLCPD7VLMGVCC4HS5Q775; ALT. DIGITAL CURRENCY ADDRESS - XBT 1EVHBAD5WCZYHBOASGACIV6AVMZ1OSLPEJ; ALT. DIGITAL CURRENCY ADDRESS - XBT BC1QSMV6LKRW65L30YAZDQPDJJTWZPVK9F8GFH0CY7; ALT. DIGITAL CURRENCY ADDRESS - XBT BC1QS9U6J78E3UTJ08MWVQKKMQM9DE5XK3G4YH8QTQ; ALT. DIGITAL CURRENCY ADDRESS - XBT 12VRYZGS1NMF9KHHPED24XBB1ALLRPV2CT; ALT. DIGITAL CURRENCY ADDRESS - XBT BC1Q202AJNHXGG9D9JJCZMG0G4USP6HAQLDYY2EAKL; ALT. DIGITAL CURRENCY ADDRESS - XBT 1NBGWQWT4UEHG2SRAKPPLF8QAF6FBP3PZG; ALT. DIGITAL CURRENCY ADDRESS - XBT 13LQJQ1OJ9K7PSQSGFJNHOVV6UEU6HGZQZ; ALT. DIGITAL CURRENCY ADDRESS - XBT 1CG1ASCXUNBMV9G34OFXTQOHTUVNMLJTQV; ALT. DIGITAL CURRENCY ADDRESS - XBT 3KP8QC5Z7YEVDEOQXHS5RSSKNEI5X7AQ43; ALT. DIGITAL CURRENCY ADDRESS - XBT 331TS6DYASY7IU5CRA8URYBNKPS78FP2B1; ALT. DIGITAL CURRENCY ADDRESS - XBT 1NVJM3JFZXENNYQWS5BKQVHKLXG9CHLJDO; ALT. DIGITAL CURRENCY ADDRESS - XBT 1LICQJCA74N8PMNAOARXLLQCTUTHFPXBXH; ALT. DIGITAL CURRENCY ADDRESS - XBT 175BUQF8JCU1UOG1ITRKTACDA4UVJDUCW2; ALT. DIGITAL CURRENCY ADDRESS - XBT 1ANPCA7G93BWPTUJG1ZV116V49ZN9GJDI3; ALT. DIGITAL CURRENCY ADDRESS - XBT 1BCWMWPR4M1NYUUUYE2BMZRNUWGOF9ZABA; ALT. DIGITAL CURRENCY ADDRESS - XBT 18CFGADYCVNHKUHXLBE7IZQKCYUW8TZCJE; ALT. DIGITAL CURRENCY ADDRESS - XBT 1QHXYULGRMHFBNPJIKV4DWHFX45HWFUMWB; ALT. DIGITAL CURRENCY ADDRESS - XBT 1GNFTY5F9QI5MFARZFGDG2JKYT5XTAHVD8; ALT. DIGITAL CURRENCY ADDRESS - XBT BC1QUYC6J8CA84Q9GJEJ5JJD2N8HRA0VFU0J60FEFS57P6E5RERKQ07Q0L5U3W; ALT. DIGITAL CURRENCY ADDRESS - XBT 16P2UWTZWXRYK5BTHNVJDDYY1D3EQGSZF2; ALT. DIGITAL CURRENCY ADDRESS - XBT 1CDDRQW7OSPRT4TT5OXKYX2LIHJDPSZY7Y; ALT. DIGITAL CURRENCY ADDRESS - XBT 1HHE61BWXS8HD2WXZWY9FQYZICBIZGESNW; ALT. DIGITAL CURRENCY ADDRESS - XBT 1D3GUAS9EQKW8DWJ9JFQTNUFDRTYSJSLXZ; ALT. DIGITAL CURRENCY ADDRESS - XBT 1PWRKXKR5AU7TC9ZPQJDHTU1EGW1QZZS4Y; ALT. DIGITAL CURRENCY ADDRESS - XBT 1D1EJ7ZQZYWWBDNXKNYPMH7HSO2U9KODG4; ALT. DIGITAL CURRENCY ADDRESS - XBT 3KGQ3HX6EFYTBJTBFSDVDKZHMWZYYWLRQH; ALT. DIGITAL CURRENCY ADDRESS - XBT 1LKE3XA9BF5JFQTGTCHZWJ5QGXKGWMFXZW; ALT. DIGITAL CURRENCY ADDRESS - XBT 1MTSQSW6N2JVJCWHPCW7JIFTFD9Q3RBBVG; ALT. DIGITAL CURRENCY ADDRESS - XBT 1KKAKUJNQWJF7CBM7JKAZGF3X9D4685M8N; ALT. DIGITAL CURRENCY ADDRESS - XBT 1GE8JODC2HIBIEUT7D3MOH6FAK6XRCT9KF; ALT. DIGITAL CURRENCY ADDRESS - XBT BC1QSMQPALP3GTGKLTAG4X3YGEVMHH9Y2HZK73T2UG; ALT. DIGITAL CURRENCY ADDRESS - XBT 1E9UUNLBYFTOAZO95VMM3YSYNZGKRL7GEC; ALT. DIGITAL CURRENCY ADDRESS - XBT 1HH8EIUATMUCTNYVGCUMAVMCZCTDMI8SQK; ALT. DIGITAL CURRENCY ADDRESS - XBT 19FQZHIBWDHSP8PKMJS3UAGFYOISXTEHZW; ALT. DIGITAL CURRENCY ADDRESS - XBT 3DLGFN7HGSWXXSP9EUXCNMWXLPFQUSWW2T; ALT. DIGITAL CURRENCY ADDRESS - XBT 1PXXWPVTYXZICRP9LKQ7AKMDFRHAQZTVUE; ALT. DIGITAL CURRENCY ADDRESS - XBT 1Q4TJJH2ABR3AJRZXQA4Z3JPPF5SDGF4JK; ALT. DIGITAL CURRENCY ADDRESS - XBT 1PYTGFS2T6I57WDDVBRA7KPCSAGGMBXZFG; ALT. DIGITAL CURRENCY ADDRESS - XBT 16ZSAEFYPPCJ3D94FSNT2OKYJ9UE8MXY6T; ALT. DIGITAL CURRENCY ADDRESS - XBT BC1QVLZFN6KMEZV44D8KW0P5JSMXE6WCHV3ZC7GSXS; ALT. DIGITAL CURRENCY ADDRESS - XBT 3QVYOH4U3QT88UCHAEJVHFB3R6MAZT431Y; ALT. DIGITAL CURRENCY ADDRESS - XBT 1FFS6PX1TCKTNY668MBK2LYOEM1QB48KYX; ALT. DIGITAL CURRENCY ADDRESS - XBT 1DPDDB1TMJVMNQEYDQGYD1WW6CMWPJRDSK; ALT. DIGITAL CURRENCY ADDRESS - XBT 3AJIWIUDKB5MCGUSS9MBEOHCEYJW3ZO8R6; ALT. DIGITAL CURRENCY ADDRESS - XBT 1ETMUBPQNPCA3CECERDSH1SZYDXNHBTMW; ALT. DIGITAL CURRENCY ADDRESS - XBT 3CCMT5LJQ5YKKAFY1DWC2SBERVETWRNSRD; ALT. DIGITAL CURRENCY ADDRESS - XBT 1MQBDERWSIJBF7K1VGJJ7PWEL6GJXMFMLG; ALT. DIGITAL CURRENCY ADDRESS - XBT 1MBTT2ZSTTLP7EKZUV9R74CTYQVSMTTP2M; ALT. DIGITAL CURRENCY ADDRESS - XBT 36YS87PLUW7SERLG1TY26WZAVARTIM7ACC; ALT. DIGITAL CURRENCY ADDRESS - XBT 3AYU365TCJEF7J9PDKF9XE8RWPEPSH196T; ALT. DIGITAL CURRENCY ADDRESS - XBT 148LKMYZT3FGE4X1GJSFN6RSAWCJZK5IUE; ALT. DIGITAL CURRENCY ADDRESS - XBT 16EKTES8AHD8XVWISQJC2XSNLIG3FDHATW; ALT. DIGITAL CURRENCY ADDRESS - XBT 3GUQJR7KKRR5EJPANMGYAUXULGRJEUWE21; ALT. DIGITAL CURRENCY ADDRESS - XBT 35EANEZ5IYG2EYAXCTMRR4SCOYPFQRBWUH; ALT. DIGITAL CURRENCY ADDRESS - XBT 3QWUDP5TAP4GRRUUEVDUD1EWETB7HC3WDH; ALT. DIGITAL CURRENCY ADDRESS - XBT 3CZHM6XQN8ODWZ6JGTCJRRUJOG28V6AVS8; ALT. DIGITAL CURRENCY ADDRESS - XBT 1F7UL41QYM6TVNEXZZPHBCYEENVX3XDEMS; ALT. DIGITAL CURRENCY ADDRESS - XBT 123WBUDMSJV4GCTDVEZ6QQ6Z8NXSKRJ4KX; ALT. DIGITAL CURRENCY ADDRESS - XBT 3BCN3WGMRJWULTZ1VSEQ7NZRBJWAUBF5CA; ALT. DIGITAL CURRENCY ADDRESS - XBT 35SWVFXOSV3ASVNRBFZDXARQAVRBVDYYXV; ALT. DIGITAL CURRENCY ADDRESS - XBT 32PCMCWEJWHKLWH5BGLNAEBQFP5GI1HV81; ALT. DIGITAL CURRENCY ADDRESS - XBT 1G64TFMFVJTJHJXRA6X74BBHSFSYIWAFTT; ALT. DIGITAL CURRENCY ADDRESS - XBT 1A3IYY4C3DKGNYGEWZYZR7ESQFBUWXIBGO; ALT. DIGITAL CURRENCY ADDRESS - XBT 3GAUBTRTTWP1D9YEXGR3WMG8B599QHA5M5; ALT. DIGITAL CURRENCY ADDRESS - XBT 3HJN4JRA4MDFKEY9JR9JUHR86YPWL86A3C; ALT. DIGITAL CURRENCY ADDRESS - XBT 1EUUMPBCZTSD5PVVFEQMRQUSFU1QY6ASUL; ALT. DIGITAL CURRENCY ADDRESS - XBT 1PU1NAW7KCOSMTHMS8QCPM8JXUBYQDZGH; ALT. DIGITAL CURRENCY ADDRESS - XBT 3QNWE5GVFQU3WVAV91RUFKQIP4TI4NWQAY; ALT. DIGITAL CURRENCY ADDRESS - XBT 1CNBHGXGRZVSWNEHOTFXGE7K2E1UPZBDC7; ALT. DIGITAL CURRENCY ADDRESS - XBT 3HSZC4BLNQBZNJSQ7JVXGQNCZUUS3M9FZZ; ALT. DIGITAL CURRENCY ADDRESS - XBT 37DDBCEXFPRAKW4JGSQKE3NYG52YEZQBJX; ALT. DIGITAL CURRENCY ADDRESS - XBT 1H8SDTTGJPBKW83EBZDLHXVETCBXZUMMZM; ALT. DIGITAL CURRENCY ADDRESS - XBT 1BVJRBRP9ZZ6ZLYUZAZSV7G3XP6JOKDZQW; ALT. DIGITAL CURRENCY ADDRESS - XBT BC1Q237MVL0HEYW0R38WD3XZ8H5MAR96RRWPAMS8PP; ALT. DIGITAL CURRENCY ADDRESS - XBT 34DXZVIJPBM1YKPYBCZBQ7DUGUKANULDFS; ALT. DIGITAL CURRENCY ADDRESS - XBT 1GKLN7DBA9MATHNZQWNPANCDWBEFAZ4GZM; ALT. DIGITAL CURRENCY ADDRESS - XBT 13HFSQM6OCADZEHFYBSMFIJVAI1JSL6SQD; ALT. DIGITAL CURRENCY ADDRESS - XBT 1SF6E4XQV8MUMZQYPTDRFF3E5O5EWCG9F; ALT. DIGITAL CURRENCY ADDRESS - XBT BC1QJ6J6P0JDEFL6PVDZX3KX8245YY5MZ6Q4LUHZES; ALT. DIGITAL CURRENCY ADDRESS - XBT 1B3U21ITZJGKTM7QSNQNCBPSKWZZEDHQRW; ALT. DIGITAL CURRENCY ADDRESS - XBT 3JHPSVV3KNL9DBYGSZALS9EBRLR97R865A; ALT. DIGITAL CURRENCY ADDRESS - XBT BC1QQF8KCC9M57XJQCVSVUF989NNL48VE6D2S24CX3; ALT. DIGITAL CURRENCY ADDRESS - XBT 1HUYFOEWSFHGZIRHBHJRCD5ST3IKSA8KEX; ALT. DIGITAL CURRENCY ADDRESS - XBT 1J9WJH2BAMZVXSCXAVODH4JVTGKB7SYFDM; ALT. DIGITAL CURRENCY ADDRESS - XBT 34WWXWFKASXL9ZYXBENPAPV6VDAMKJQLUO; ALT. DIGITAL CURRENCY ADDRESS - XBT 3PDMRWOTTKRAFRLGTURUCCERP2JDM1Q4AR; ALT. DIGITAL CURRENCY ADDRESS - XBT 3AFCE2MBSSNDCPYFGHOEXSMJUC26EF2GQH; ALT. DIGITAL CURRENCY ADDRESS - XBT 3P6PZDFETR4275GN3VELKCYDXA1JV8FHKM; ALT. DIGITAL CURRENCY ADDRESS - XBT 3HREXD8GKFSKZC5INMVCPIYY9UWG7FVA6O; ALT. DIGITAL CURRENCY ADDRESS - XBT 3MP7YBGSW2GKXVRE8S84T2J4KVGPH3REZV; ALT. DIGITAL CURRENCY ADDRESS - XBT 1K2FME9HFHBRNSZOBVCBWZAVSS5IDTUXBG; ALT. DIGITAL CURRENCY ADDRESS - XBT 3ES6PQCUEDPCNC4HCQHHYUEY6GYIRJZW6E; ALT. DIGITAL CURRENCY ADDRESS - XBT 3KVBX3JO69QN8JHY44M33RYOEYCF8DDRBD; ALT. DIGITAL CURRENCY ADDRESS - XBT 3K26AMKMNRV97PJ6YIFCQIXK2LXEHFHNG3; ALT. DIGITAL CURRENCY ADDRESS - XBT 3BWP6ZQAHC4J5WR1B95ZJATHJEFVHDEES7; ALT. DIGITAL CURRENCY ADDRESS - XBT 3JUSGFRWNRNFUHVR4GPWAPMEJVOT4XREAE; ALT. DIGITAL CURRENCY ADDRESS - XBT 1DKGRGJXGNLATTEFB9SNPNHTRKZ87Q7QKI; ALT. DIGITAL CURRENCY ADDRESS - XBT 361AKMKNNWYWZRSCE8PPNMOH5AQF4V7G4P; ALT. DIGITAL CURRENCY ADDRESS - XBT 33FWCMDMSB2EY4CEBVWBJGFKUEVBSYP9NG; ALT. DIGITAL CURRENCY ADDRESS - XBT 35ATJKBH4YETYPJSI9NUTDOMKHTSAWKVGX; SECONDARY SANCTIONS RISK: UKRAINE-/RUSSIA-RELATED SANCTIONS REGULATIONS, 31 CFR 589.201; ORGANIZATION ESTABLISHED DATE 2015; A.K.A. 'HYDRA'.";

    char charArray2[] = "The behavior is undefined if the destination array is not large enough for the contents of both src and dest and the terminating null character.";

    std::strcat(charArray, charArray2);
    std::strcat(charArray, " Goodbye World!");

    // std::cout << charArray << std::endl;

    MyStruct myStruct;
    string str = "abc";

    string result = combineExtraData(myStruct.charArray, str);
    std::cout << result << std::endl;


    int value = 0;
    if (value)
    {
        // Cpp 中非0为真，0为假
        std::cout << "value not 0" << std::endl;
    }
    else {
        std::cout << "value0" << std::endl;
    }


    // 直接判断是否为空
    const char* pointer = "c";
    if (!pointer) {
        std::cout << "Test" << std::endl;
    }
    else {
        std::cout << "not null" << std::endl;
    }
    std::cout << *pointer << std::endl;
    pointer = NULL;
    // std::cout << *pointer << std::endl;


    // CPP的连续赋值
    // ossExpectedBIC << "strFirstTokenValue" << "strSecondTokenValue";


    std::string check = "BOSNIA";
    if (std::find(values.begin(), values.end(), check) != values.end())
    {
        std::cout << "Found" << std::endl;
    }
    else {
        std::cout << "Not Found" << std::endl;
    }




    const char* addInfoItem = "new test";

    if (addInfoItem == "new test") {
        std::cout << "test add info ok" << std::endl;
    }

    if (strcmp(addInfoItem, "new test") == 0) {
        std::cout << "test add info ok" << std::endl;
    }


    int pdwFileLength = 0;
    char* m_szMemMapping;
    std::string strRulBuffer = "this is a test\n";

    pdwFileLength = strRulBuffer.size() + 1;
    m_szMemMapping = new char[pdwFileLength];
    strcpy(m_szMemMapping, strRulBuffer.c_str());

    std::cout << pdwFileLength << std::endl;
    std::cout << m_szMemMapping << std::endl;


    std::cout << "----------" << std::endl;
    char* m_szMemMapping2 = new char[4096]();

    char* pchDataRule = new char[4097];;
    strcpy(pchDataRule, m_szMemMapping2);

    std::cout << strlen(pchDataRule) << std::endl;


    // string strValue = "test chen \n\n";
    // char* ptr = (char *) strValue.c_str();
    // cout << strlen(ptr) << endl;
    // 
    // 
    // cout << sizeof(ptr) << endl;
    // 
    // int size = strValue.size();
    // if (ptr[size - 1] == '\n' && ptr[size - 2] == '\n')
    // {
    //     cout << "Find enter at end" << endl;
    // }
    // 
    // for (int index = 0; index < strValue.size(); index++) {
    //     std::cout << ptr[index] << std::endl;
    // }
    // 
    // cout << "end" << endl;

    return 0;
}
